### ISSUE TITLE
Issues with mutationsTSV input

### ISSUE THREAD

**Issue by jmcbroome** [NicolaDM/phastSim#18]
I'm trying to use phastSim to simulate mutations onto the newick output from [VGsim](https://github.com/Genomics-HSE/VGsim). Accordingly, I'm using `--mutationsTSVinput` to pass haplotype information from my VGsim simulations. However, phastSim fails with the following traceback when attempting to apply said mutations: 

```
Traceback (most recent call last):
  File "/Users/jmcbr/opt/anaconda3/envs/vgsim/bin/phastSim", line 174, in <module>
    genome_tree.mutateBranchETEhierarchy(t, genome_tree.genomeRoot, 1, sim_run.args.createNewick, preMutationsBranches)
  File "/Users/jmcbr/opt/anaconda3/envs/vgsim/lib/python3.10/site-packages/phastSim/phastSim.py", line 1538, in mutateBranchETEhierarchy
    self.mutateBranchETEhierarchy(c, newGenomeNode, level + 1, createNewick, preMutationsBranches)
  File "/Users/jmcbr/opt/anaconda3/envs/vgsim/lib/python3.10/site-packages/phastSim/phastSim.py", line 1538, in mutateBranchETEhierarchy
    self.mutateBranchETEhierarchy(c, newGenomeNode, level + 1, createNewick, preMutationsBranches)
  File "/Users/jmcbr/opt/anaconda3/envs/vgsim/lib/python3.10/site-packages/phastSim/phastSim.py", line 1538, in mutateBranchETEhierarchy
    self.mutateBranchETEhierarchy(c, newGenomeNode, level + 1, createNewick, preMutationsBranches)
  [Previous line repeated 7 more times]
  File "/Users/jmcbr/opt/anaconda3/envs/vgsim/lib/python3.10/site-packages/phastSim/phastSim.py", line 1481, in mutateBranchETEhierarchy
    self.applyMutation(newGenomeNode, level, mutEvent)
  File "/Users/jmcbr/opt/anaconda3/envs/vgsim/lib/python3.10/site-packages/phastSim/phastSim.py", line 1397, in applyMutation
    node = parentGenomeNode.refNode
AttributeError: 'genomeNode' object has no attribute 'refNode'
```

It appears to be attempting to access uninitalized attributes- the genomeNode object passed as input to applyMutations in the recursive step (newGenomeNode, in mutateBranchETEhierarchy, line 1472) never has these attributes defined in its \_\_init\_\_ or afterwards. mutationsTSV input requires the hierarchical mode, so I cannot work around this. 

I should note that I installed the latest version today simply with 

```
pip install phastsim
```

So this is a current issue.

**Comment by willboulton** [comment]
Hi Jacob, thanks for raising this issue - sorry for the slow reply! I will take a look - I think you're quite right about where the problem is coming from. Hopefully it should be simple to fix by ensuring that these nodes all have the correct reference node supplied to them when starting the simulation. Best wishes, Will

**Comment by willboulton** [comment]
Hi Jacob - sorry for the delay but hopefully the last update to the pypi repository (v0.0.5) has fixed the issue... the commit prior to that should have fixed the github version!
